name: GCP Integration Pipeline
on:
  push:
    branches:
      - main
      - developer

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Repositorio de check-out
        uses: actions/checkout@v2

      - name: Configurar o Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Configurar SDK do Google Cloud
        uses: google-github-actions/setup-gcloud@master
        with:
          version: 'latest'
          service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Configure Docker
        run: |
          echo ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }} | base64 --decode > key.json
          gcloud auth activate-service-account --key-file=key.json
          gcloud auth configure-docker

      - name: Criar imagem do Docker
        run: docker build -t python:3.9 .

      - name: Tag imagem Docker
        run: docker tag python:3.9 gcr.io/python:3.9

      - name: Enviar imagem do Docker para GCR
        run: docker push gcr.io/grupo-03-390620/python:3.9

      - name: Iniciar o Docker Compose
        run: docker-compose up -d
