name: Canal de integração do GCP - SPOTMUSIC - BackEnd
on:
  push:
    branches:
      - main
      - developer

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Repositorio de check-out
        uses: actions/checkout@v2

      - name: Configurar o Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Criar imagem do Docker
        run: docker build -t python:3.9 .

      - name: Logar em GCR
        uses: docker/login-action@v1
        with:
          registry: gcr.io
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Enviar imagem do Docker para GCR
        run: docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/python:3.9

      - name: Iniciar o Docker Compose
        run: docker-compose up -d
